# Generated by Django 4.2.7 on 2026-06-01 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام دسته")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "دسته منو",
                "verbose_name_plural": "دسته\u200cهای منو",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام رستوران")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="طول جغرافیایی"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="عرض جغرافیایی"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="شماره تلفن"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="restaurant_logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="restaurant_covers/"
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("persian", "ایرانی"),
                            ("fast_food", "فست فود"),
                            ("italian", "ایتالیایی"),
                            ("chinese", "چینی"),
                            ("japanese", "ژاپنی"),
                            ("dessert", "دسر و شیرینی"),
                            ("cafe", "کافه"),
                            ("other", "سایر"),
                        ],
                        default="persian",
                        max_length=20,
                        verbose_name="نوع غذا",
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="حداقل سفارش",
                    ),
                ),
                (
                    "delivery_time",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="زمان تخمینی تحویل به دقیقه",
                        verbose_name="زمان تحویل",
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="باز است")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="تأیید شده"),
                ),
                (
                    "is_busy",
                    models.BooleanField(default=False, verbose_name="مشغول است"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "max_concurrent_orders",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="حداکثر سفارش\u200cهای همزمان",
                        verbose_name="حداکثر سفارش همزمان",
                    ),
                ),
                (
                    "current_orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد سفارش\u200cهای جاری"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "restaurant_owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "رستوران",
                "verbose_name_plural": "رستوران\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام غذا")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="قیمت",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="موجودی"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="موجود است"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu_items/"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "is_vegetarian",
                    models.BooleanField(default=False, verbose_name="گیاه\u200cخواری"),
                ),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="زمان آماده\u200cسازی به دقیقه",
                        verbose_name="زمان آماده\u200cسازی",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "موجود"),
                            ("unavailable", "ناموجود"),
                            ("coming_soon", "به زودی"),
                        ],
                        default="available",
                        max_length=15,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurants.menucategory",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم منو",
                "verbose_name_plural": "آیتم\u200cهای منو",
                "ordering": ["category__order", "name"],
            },
        ),
        migrations.AddField(
            model_name="menucategory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["latitude", "longitude"], name="restaurants_latitud_bcb1fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["is_open", "is_active"], name="restaurants_is_open_b95c60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["cuisine_type"], name="restaurants_cuisine_01615e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["owner"], name="restaurants_owner_i_a6fa17_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["restaurant", "is_available"],
                name="restaurants_restaur_1087ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category"], name="restaurants_categor_1ec52e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("restaurant", "name")},
        ),
    ]
