# Generated by Django 4.2.7 on 2026-06-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_restaurantreview_favoriterestaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(default="تهران", max_length=100, verbose_name="شهر"),
        ),
    ]
