# Generated by Django 4.2.7 on 2026-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_restaurant_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="عرض جغرافیایی"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="طول جغرافیایی"
            ),
        ),
    ]
