# Generated by Django 4.2.7 on 2026-06-01 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام منطقه")),
                (
                    "center_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "center_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "radius_km",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "extra_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "منطقه تحویل",
                "verbose_name_plural": "مناطق تحویل",
            },
        ),
        migrations.CreateModel(
            name="PeakTimeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "دوشنبه"),
                            (1, "سه\u200cشنبه"),
                            (2, "چهارشنبه"),
                            (3, "پنجشنبه"),
                            (4, "جمعه"),
                            (5, "شنبه"),
                            (6, "یکشنبه"),
                        ],
                        verbose_name="روز هفته",
                    ),
                ),
                (
                    "start_hour",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                (
                    "end_hour",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ]
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "تنظیم زمان شلوغی",
                "verbose_name_plural": "تنظیمات زمان شلوغی",
                "unique_together": {("day_of_week", "start_hour", "end_hour")},
            },
        ),
        migrations.CreateModel(
            name="RiderLocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "speed_kmh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bearing",
                    models.IntegerField(
                        blank=True, help_text="جهت حرکت بر حسب درجه", null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "active_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        limit_choices_to={"role": "delivery_rider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه موقعیت راننده",
                "verbose_name_plural": "تاریخچه موقعیت رانندگان",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["rider", "-recorded_at"],
                        name="delivery_ri_rider_i_2f026d_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="delivery_ri_recorde_cf4e73_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("pickup", "در مسیر رستوران"),
                            ("at_restaurant", "رسیده به رستوران"),
                            ("picked_up", "تحویل گرفته شد"),
                            ("delivering", "در مسیر مشتری"),
                            ("delivered", "تحویل داده شد"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت تحویل",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("pickup_started_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at_restaurant", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "restaurant_arrival_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "restaurant_arrival_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pickup_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_traveled_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "time_to_restaurant_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "time_to_delivery_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        limit_choices_to={"status__in": ["delivering", "delivered"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking",
                        to="orders.order",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        limit_choices_to={"role": "delivery_rider"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_trackings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ردیابی تحویل",
                "verbose_name_plural": "ردیابی\u200cهای تحویل",
                "indexes": [
                    models.Index(
                        fields=["status"], name="delivery_de_status_c57560_idx"
                    ),
                    models.Index(
                        fields=["rider", "status"],
                        name="delivery_de_rider_i_401125_idx",
                    ),
                    models.Index(
                        fields=["order"], name="delivery_de_order_i_67b594_idx"
                    ),
                ],
            },
        ),
    ]
