# Generated by Django 4.2.7 on 2026-06-01 19:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد خرید",
                "verbose_name_plural": "سبدهای خرید",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="جمع سفارش"
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="هزینه ارسال",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="تخفیف"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قابل پرداخت"
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="آدرس تحویل")),
                (
                    "customer_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="طول جغرافیایی مشتری",
                    ),
                ),
                (
                    "customer_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="عرض جغرافیایی مشتری",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("preparing", "در حال آماده\u200cسازی"),
                            ("ready", "آماده تحویل"),
                            ("delivering", "در مسیر تحویل"),
                            ("delivered", "تحویل داده شده"),
                            ("cancelled", "لغو شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدی"),
                            ("card", "کارت بانکی"),
                            ("online", "آنلاین"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_delivery_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تخمینی تحویل"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="مسافت برحسب کیلومتر",
                    ),
                ),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        default=0, help_text="زمان آماده\u200cسازی به دقیقه"
                    ),
                ),
                (
                    "customer_note",
                    models.TextField(blank=True, verbose_name="یادداشت مشتری"),
                ),
                (
                    "rider_note",
                    models.TextField(blank=True, verbose_name="یادداشت راننده"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "delivery_rider"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت واحد"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="جمع"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=255, verbose_name="نام آیتم"),
                ),
                (
                    "item_description",
                    models.TextField(blank=True, verbose_name="توضیحات آیتم"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="restaurants.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="restaurants.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سبد خرید",
                "verbose_name_plural": "آیتم\u200cهای سبد خرید",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "status"], name="orders_orde_restaur_17016b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["rider", "status"], name="orders_orde_rider_i_46406c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="orders_orde_custome_c9b64a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="orders_orde_created_0e92de_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "menu_item")},
        ),
    ]
